server:
  port: 80
# 快鸟物流查询配置
kuainiao:
  express:
    enable: true
    appId: 1831866
    appKey: 8240860b-dfb5-4921-ac2f-eea585885eb6
    expressQueryUrl: https://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx
    requestType: 1002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:acmeshop}?allowMultiQueries=true
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  jackson:
    #  格式化返回时间 yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置时区
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.acme.acmemall: debug

